### ISSUE TITLE
大佬，已经star，请问该项目修改前端后，浏览器不自动刷新，什么原因？需要设置才能生效？

### ISSUE THREAD

**Issue by arraycto** [zhangyao1990/admin-vue3-elementplus#1]
大佬，已经star，请问该项目修改前端后，浏览器不自动刷新，什么原因？需要设置才能生效？

**Comment by zhangyao1990** [comment]
热更新是正常的。。

**Comment by zhangyao1990** [comment]
devServer里面加这个
		disableHostCheck: true,//webpack4.0 开启热更新

**Comment by dogbaha** [comment]
> 大佬，已经star，请问该项目修改前端后，浏览器不自动刷新，什么原因？需要设置才能生效？

同学，我是微动项目设计开发者，微动是我们当初参加比赛的作品，代码里面有我的个人信息，已经有好几个人通过里面的联系方式找我了，我不知道你从哪里搞来的源码，请你马上删掉微动的仓库。
